/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import jargo.pkg4.pkg0.Comand;
import jargo.pkg4.pkg0.Sql;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JDialog {

    /**
     * Creates new form Menu
     */
    
    java.awt.Frame parent;
    public Menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        new Thread(){
            public void run(){
                atualizar();
                JLabel[] botoes = new JLabel[]{
                    Item2,Item3,Item4,Item5,Item6,Item7
                };
                m = new Sql().Menu();
                int i = 0;
                jLabel1.setText("1-"+m.size()/6);
                for (JLabel botoe : botoes) {
                    if(m.size() >= i){
                        botoe.setText(m.get(i).getNome());
                        botoe.setName(m.get(i).getComando());
                        botoe.addMouseListener(listener);
                    }else{
                        botoe.setVisible(false);
                    }
                    i++;
                }
            }
        }.start();
    }
    ArrayList<MenuPropriedade> m;
    MouseListener listener = new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getSource() instanceof JLabel) {
                    String text = ((JLabel) e.getSource()).getName();
                    new Comand().result(text);
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                int cor = Integer.valueOf(((JLabel) e.getSource()).getBackground().getRGB());
                int cor2 = Integer.valueOf(((JLabel) e.getSource()).getForeground().getRGB());
                ((JLabel) e.getSource()).setBackground(new Color(cor*-1));
                ((JLabel) e.getSource()).setForeground(new Color(cor2*-1));
            }
            @Override
            public void mouseExited(MouseEvent e) {
                int cor = Integer.valueOf(((JLabel) e.getSource()).getBackground().getRGB());
                int cor2 = Integer.valueOf(((JLabel) e.getSource()).getForeground().getRGB());
                ((JLabel) e.getSource()).setBackground(new Color(cor*-1));
                ((JLabel) e.getSource()).setForeground(new Color(cor2*-1));
            }
            
        };
    private void atualizar(int index){
        JLabel[] botoes = new JLabel[]{
            Item2,Item3,Item4,Item5,Item6,Item7
        };
        int i = index;
            for (JLabel botoe : botoes) {
                botoe.setVisible(true);
                if(i < m.size() && i >= 0){
                    botoe.setText(m.get(i).getNome());
                    botoe.setName(m.get(i).getComando());
//                    botoe.addMouseListener(listener);
                }else{
                    botoe.setVisible(false);
                }
                i++;
                }
    }
    
    private void atualizar(){
        JLabel[] cor1 = new JLabel[]{
            Item1,Item2,Item3,Item4,Item5,Item6,Item7,Barra
        };
        Data o = new Data();
        for(JLabel e : cor1){
            e.setBackground(o.getCor2());
            e.setForeground(o.getCorFonte());
        }
        Fundo.setBackground(o.getCor1());
        Fundo.setForeground(o.getCorFonte());
        setAlwaysOnTop(o.isSobreTela());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fundo = new javax.swing.JPanel();
        Proximo = new javax.swing.JLabel();
        Anterior = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Item1 = new javax.swing.JLabel();
        Item2 = new javax.swing.JLabel();
        Item3 = new javax.swing.JLabel();
        Item4 = new javax.swing.JLabel();
        Item5 = new javax.swing.JLabel();
        Item6 = new javax.swing.JLabel();
        Item7 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        Barra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Fundo.setBackground(new java.awt.Color(31, 32, 34));
        Fundo.setForeground(new java.awt.Color(39, 41, 38));

        Proximo.setBackground(new java.awt.Color(251, 255, 255));
        Proximo.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Proximo.setForeground(new java.awt.Color(39, 41, 38));
        Proximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Proximo.setText("Proximo");
        Proximo.setOpaque(true);
        Proximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProximoMouseClicked(evt);
            }
        });

        Anterior.setBackground(new java.awt.Color(251, 255, 255));
        Anterior.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Anterior.setForeground(new java.awt.Color(39, 41, 38));
        Anterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Anterior.setText("Anterior");
        Anterior.setOpaque(true);
        Anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnteriorMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0-0");

        Item1.setBackground(new java.awt.Color(39, 41, 38));
        Item1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Item1.setForeground(new java.awt.Color(255, 255, 255));
        Item1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item1.setText("Opções");
        Item1.setOpaque(true);
        Item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Item1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item1MouseExited(evt);
            }
        });

        Item2.setBackground(new java.awt.Color(39, 41, 38));
        Item2.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Item2.setForeground(new java.awt.Color(255, 255, 255));
        Item2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item2.setText("Item1");
        Item2.setOpaque(true);

        Item3.setBackground(new java.awt.Color(39, 41, 38));
        Item3.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Item3.setForeground(new java.awt.Color(255, 255, 255));
        Item3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item3.setText("Item1");
        Item3.setOpaque(true);

        Item4.setBackground(new java.awt.Color(39, 41, 38));
        Item4.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Item4.setForeground(new java.awt.Color(255, 255, 255));
        Item4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item4.setText("Item1");
        Item4.setOpaque(true);

        Item5.setBackground(new java.awt.Color(39, 41, 38));
        Item5.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Item5.setForeground(new java.awt.Color(255, 255, 255));
        Item5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item5.setText("Item1");
        Item5.setOpaque(true);

        Item6.setBackground(new java.awt.Color(39, 41, 38));
        Item6.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Item6.setForeground(new java.awt.Color(255, 255, 255));
        Item6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item6.setText("Item1");
        Item6.setOpaque(true);

        Item7.setBackground(new java.awt.Color(39, 41, 38));
        Item7.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Item7.setForeground(new java.awt.Color(255, 255, 255));
        Item7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Item7.setText("Item1");
        Item7.setOpaque(true);

        Voltar.setBackground(new java.awt.Color(251, 255, 255));
        Voltar.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(39, 41, 38));
        Voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Voltar.setText("Voltar");
        Voltar.setOpaque(true);
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
        });

        Barra.setBackground(new java.awt.Color(39, 41, 38));
        Barra.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        Barra.setForeground(new java.awt.Color(255, 255, 255));
        Barra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Barra.setText("MENU");
        Barra.setOpaque(true);

        javax.swing.GroupLayout FundoLayout = new javax.swing.GroupLayout(Fundo);
        Fundo.setLayout(FundoLayout);
        FundoLayout.setHorizontalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Item2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Item3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Item4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Item5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Item6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Item7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FundoLayout.createSequentialGroup()
                        .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLayout.createSequentialGroup()
                        .addComponent(Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        FundoLayout.setVerticalGroup(
            FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FundoLayout.createSequentialGroup()
                .addComponent(Barra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
//        setAlwaysOnTop(new Data().getSobreTela());
        dispose();
    }//GEN-LAST:event_VoltarMouseClicked
    private int posicao;
    private int p = 1;
    private void ProximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProximoMouseClicked
        if(posicao < m.size()-6){
            atualizar(posicao += 6);
            jLabel1.setText((p+=1)+"-"+m.size()/6);
        }
    }//GEN-LAST:event_ProximoMouseClicked

    private void AnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnteriorMouseClicked
        if(posicao > 0){
            atualizar(posicao -= 6);
            jLabel1.setText((p-=1)+"-"+m.size()/6);
        }
    }//GEN-LAST:event_AnteriorMouseClicked

    private void Item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item1MouseClicked
        Opcoes fr = new Opcoes(parent, true);
        this.dispose();
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        int xlabel = evt.getX();
        int ylabel = evt.getY();
        fr.setLocation(x-xlabel, y-ylabel);
        fr.setVisible(true);
        atualizar();
        int cor = Integer.valueOf(Item1.getBackground().getRGB());
        int cor2 = Integer.valueOf(Item1.getForeground().getRGB());
        Item1.setBackground(new Color(cor*-1));
        Item1.setForeground(new Color(cor2*-1));
        
    }//GEN-LAST:event_Item1MouseClicked

    private void Item1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item1MouseEntered
        int cor = Integer.valueOf(Item1.getBackground().getRGB());
        int cor2 = Integer.valueOf(Item1.getForeground().getRGB());
        Item1.setBackground(new Color(cor*-1));
        Item1.setForeground(new Color(cor2*-1));
    }//GEN-LAST:event_Item1MouseEntered

    private void Item1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item1MouseExited
        int cor = Integer.valueOf(Item1.getBackground().getRGB());
        int cor2 = Integer.valueOf(Item1.getForeground().getRGB());
        Item1.setBackground(new Color(cor*-1));
        Item1.setForeground(new Color(cor2*-1));
    }//GEN-LAST:event_Item1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu dialog = new Menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anterior;
    private javax.swing.JLabel Barra;
    private javax.swing.JPanel Fundo;
    private javax.swing.JLabel Item1;
    private javax.swing.JLabel Item2;
    private javax.swing.JLabel Item3;
    private javax.swing.JLabel Item4;
    private javax.swing.JLabel Item5;
    private javax.swing.JLabel Item6;
    private javax.swing.JLabel Item7;
    private javax.swing.JLabel Proximo;
    private javax.swing.JLabel Voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
