/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author User
 */
public class Opcoes extends javax.swing.JDialog {

    /**
     * Creates new form Opcoes
     */
    Data saida = new Data();
    public Opcoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        new Thread(){
            public void run(){
                atualizar();
                setAlwaysOnTop(false);
            }
        }.start();
        
    }
    private Data cancelar;
    private void atualizar(){
        
        Cor1.setBackground(saida.getCor1());
        Cor2.setBackground(saida.getCor2());
        Cor3.setBackground(saida.getCorFonte());
        
        Fundo6.setBackground(saida.getCor1());
        Fundo7.setBackground(saida.getCor1());
        Fundo8.setBackground(saida.getCor1());
        
        jTextField1.setBackground(saida.getCor2());
        jLabel5.setBackground(saida.getCor2());
        jPanel7.setBackground(saida.getCor2());
        
        jTextField1.setForeground(saida.getCorFonte());
        Horas6.setForeground(saida.getCorFonte());
        BtnEnviar.setBackground(saida.getCorFonte());
        Fundo7.setForeground(saida.getCorFonte());
        
        Sobre.setSelected(saida.isSobreTela());
        rDireta.setSelected(saida.isRespostaDireta());
        setAlwaysOnTop(saida.isSobreTela());
        
//        Image[] img = new Botoes().trocarCor(new Data().getCorFonte());
//        JLabel[] labels = new JLabel[]{BtnFechar5, BtnMin5, BtnMenu5};
//        int i = 0;
//        for(JLabel botao : labels){
//            ImageIcon icon = new ImageIcon(img[i]);
//            botao.setIcon(icon);
//            i++;
//        }
//        new Botoes().trocarCor(saida.getCorFonte());
//        
//        URL url     = this.getClass().getResource("/res/result0.png");
//        URL url2     = this.getClass().getResource("/res/result1.png");
//        URL url3     = this.getClass().getResource("/res/result2.png");
//        
//        try{
//            BufferedImage[] imga = new BufferedImage[]{
//                    ImageIO.read( new File(url.toURI())),
//                    ImageIO.read( new File(url2.toURI())),
//                    ImageIO.read( new File(url3.toURI()))
//                };
//            JLabel[]    labels = new JLabel[]{BtnFechar5, BtnMin5, BtnMenu5};
//            int i = 0;
//            for(JLabel botao : labels){
//                ImageIcon icone = new ImageIcon(imga[i].getScaledInstance(18, 18, Image.SCALE_SMOOTH));
//                botao.setIcon(icone);
//                i++;
//            }
//        }catch(IOException | URISyntaxException ex){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Horas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Cor1 = new javax.swing.JLabel();
        Cor2 = new javax.swing.JLabel();
        Cor3 = new javax.swing.JLabel();
        Sobre = new javax.swing.JCheckBox();
        Fundo6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Horas6 = new javax.swing.JLabel();
        BtnMenu5 = new javax.swing.JLabel();
        BtnFechar5 = new javax.swing.JLabel();
        BtnMin5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Fundo7 = new javax.swing.JTextArea();
        Fundo8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnEnviar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rDireta = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ok");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Horas.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        Horas.setForeground(new java.awt.Color(251, 255, 255));
        Horas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horas.setText("OPÇÕES");
        jPanel1.add(Horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 0, 52, 30));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Cor1.setBackground(new java.awt.Color(0, 0, 0));
        Cor1.setOpaque(true);
        Cor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cor1MouseClicked(evt);
            }
        });

        Cor2.setBackground(new java.awt.Color(0, 0, 0));
        Cor2.setOpaque(true);
        Cor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cor2MouseClicked(evt);
            }
        });

        Cor3.setBackground(new java.awt.Color(0, 0, 0));
        Cor3.setOpaque(true);
        Cor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cor3MouseClicked(evt);
            }
        });

        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });

        Fundo6.setBackground(new java.awt.Color(31, 32, 34));

        jPanel7.setBackground(new java.awt.Color(39, 41, 38));

        Horas6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        Horas6.setForeground(new java.awt.Color(251, 255, 255));
        Horas6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Horas6.setText("JARGO");

        BtnMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/menu.png"))); // NOI18N
        BtnMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnFechar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/fechar.png"))); // NOI18N
        BtnFechar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BtnMin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/mini.png"))); // NOI18N
        BtnMin5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(BtnMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(Horas6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(BtnMin5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnFechar5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Horas6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMin5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFechar5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Fundo7.setEditable(false);
        Fundo7.setBackground(new java.awt.Color(31, 32, 34));
        Fundo7.setColumns(20);
        Fundo7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Fundo7.setForeground(new java.awt.Color(251, 255, 255));
        Fundo7.setLineWrap(true);
        Fundo7.setRows(5);
        Fundo7.setText("Jargo: Demonstração");
        Fundo7.setWrapStyleWord(true);
        Fundo7.setBorder(null);
        jScrollPane1.setViewportView(Fundo7);

        Fundo8.setBackground(new java.awt.Color(31, 32, 34));

        jTextField1.setBackground(new java.awt.Color(39, 41, 38));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(251, 255, 255));
        jTextField1.setText("Escreva uma mensagem...");
        jTextField1.setBorder(null);

        jLabel5.setBackground(new java.awt.Color(39, 41, 38));
        jLabel5.setOpaque(true);

        BtnEnviar.setBackground(new java.awt.Color(251, 255, 255));
        BtnEnviar.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        BtnEnviar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEnviar.setOpaque(true);

        javax.swing.GroupLayout Fundo8Layout = new javax.swing.GroupLayout(Fundo8);
        Fundo8.setLayout(Fundo8Layout);
        Fundo8Layout.setHorizontalGroup(
            Fundo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fundo8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(Fundo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Fundo8Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(BtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Fundo8Layout.setVerticalGroup(
            Fundo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fundo8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(Fundo8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Fundo8Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout Fundo6Layout = new javax.swing.GroupLayout(Fundo6);
        Fundo6.setLayout(Fundo6Layout);
        Fundo6Layout.setHorizontalGroup(
            Fundo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fundo6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fundo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fundo6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        Fundo6Layout.setVerticalGroup(
            Fundo6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fundo6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fundo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cor de fundo");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cor da barra e entrada de texto");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cor de fundo");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sobre todas as janelas");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Resposta direta");

        rDireta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDiretaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rDireta))
                        .addComponent(Fundo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Cor3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Sobre)))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(434, 434, 434)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Cor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cor3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sobre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rDireta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fundo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Cor1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Cor2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(427, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cor1MouseClicked
        JColorChooser cor = new JColorChooser();
        Color color = cor.showDialog(cor, "Escolha uma cor", saida.getCor1());
        if(color == null)
            return;
        saida.setCor1(color);
        atualizar();
    }//GEN-LAST:event_Cor1MouseClicked

    private void Cor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cor2MouseClicked
        JColorChooser cor = new JColorChooser();
        Color color = cor.showDialog(cor, "Escolha uma cor", saida.getCor2());
        if(color == null)
            return;
        saida.setCor2(color);
        atualizar();
    }//GEN-LAST:event_Cor2MouseClicked

    private void Cor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cor3MouseClicked
        JColorChooser cor = new JColorChooser();
        Color color = cor.showDialog(cor, "Escolha uma cor", saida.getCorFonte());
        if(color == null)
            return;
        
        Fundo7.setForeground(color);
        jTextField1.setForeground(color);
        Horas6.setForeground(color);
        BtnEnviar.setBackground(color);

        Cor3.setBackground(color);
        saida.setCorFonte(color);
//        Image[] img = new Botoes().trocarCor(new Data().getCorFonte());
//        JLabel[] labels = new JLabel[]{BtnFechar5, BtnMin5, BtnMenu5};
//        int i = 0;
//        for(JLabel botao : labels){
//            ImageIcon icon = new ImageIcon(img[i]);
//            botao.setIcon(icon);
//            i++;
//        }
        atualizar();
        
    }//GEN-LAST:event_Cor3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        saida.setSobreTela(Sobre.isSelected());
        saida.setRespostaDireta(rDireta.isSelected());
        saida.Salvar();
        
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x-xMouse2, y-yMouse2);
    }//GEN-LAST:event_jPanel1MouseDragged
    private int xMouse;
    private int yMouse;
    private int xMouse2;
    private int yMouse2;
    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        xMouse2 = evt.getX();
        yMouse2 = evt.getY();
    }//GEN-LAST:event_jPanel1MouseMoved

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SobreActionPerformed

    private void rDiretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDiretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rDiretaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Opcoes dialog = new Opcoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnEnviar;
    private javax.swing.JLabel BtnFechar5;
    private javax.swing.JLabel BtnMenu5;
    private javax.swing.JLabel BtnMin5;
    private javax.swing.JLabel Cor1;
    private javax.swing.JLabel Cor2;
    private javax.swing.JLabel Cor3;
    private javax.swing.JPanel Fundo6;
    private javax.swing.JTextArea Fundo7;
    private javax.swing.JPanel Fundo8;
    private javax.swing.JLabel Horas;
    private javax.swing.JLabel Horas6;
    private javax.swing.JCheckBox Sobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox rDireta;
    // End of variables declaration//GEN-END:variables
}
